### PR TITLE
Remove wit-abi stuff we are not using

### PR DESCRIPTION
**Pull request by yamt**
It's just confusing to have unmaintained files. Let's remove them.
When/if we change our mind, it's trivial to revive them.

### CODE REVIEW

**Comment by yamt** [comment]
> I would prefer to just fix the CI errors instead since having a WIT specification is the most formal part of this proposal.

https://github.com/WebAssembly/wasi-threads/pull/24

**Comment by loganek** [comment]
@yamt can we close this PR? The CI is green now thanks to your change (https://github.com/WebAssembly/wasi-threads/pull/24) and we'll continue updates here: https://github.com/WebAssembly/wasi-threads/pull/26

**Comment by yamt** [comment]
> @yamt can we close this PR? The CI is green now thanks to your change (#24) and we'll continue updates here: #26

i will close this once #26 is merged.

**Comment by loganek** [comment]
https://github.com/WebAssembly/wasi-threads/pull/26 is merged, I'm closing this PR

**Pull request closed without merging**
